name: 'Hello World'
description: 'Greet someone'  
inputs:
  NWPS_ARTIFACTORY_URL:
    description: 'Artifactory Url'
    required: true
  NWPS_ARTIFACTORY_USERNAME:
    required: true
  NWPS_ARTIFACTORY_PASSWORD:
    required: true
outputs:
  jfrog-token:
    description: "JFrog Access Token"
    value: ${{ steps.random-number-generator.outputs.random-id }} 
runs:
  using: "composite"
  steps:
  - name: Setup JFrog CLI
    uses: jfrog/setup-jfrog-cli@v1
      
  - run: |
      echo "----------------------------------"
      echo ${{ inputs.NWPS_ARTIFACTORY_URL }}
      echo ${{ inputs.NWPS_ARTIFACTORY_USERNAME }}
      echo "----------------------------------"

      jfrog -v
      jfrog config add --artifactory-url=${{ inputs.NWPS_ARTIFACTORY_URL }} --user=${{ inputs.NWPS_ARTIFACTORY_USERNAME }} --password=${{ inputs.NWPS_ARTIFACTORY_PASSWORD }} --enc-password=false TESTSERVER
      jfrog rt ping
      jfrog rt atc 
      token=$(jfrog rt atc)
      echo $token
      #--url=${{ env.ARTIFACTORY_URL }} --user=${{ env.ARTIFACTORY_USERNAME }} --password=${{ env.ARTIFACTORY_PASSWORD }}
      
      
    shell: bash
    #- run: | 
    #    echo Hello ${{ inputs.who-to-greet }} >> ${{ github.action_path }}/test.log
    #    ls ${{ github.action_path }}
    #    cat ${{ github.action_path }}/test.log
    #  shell: bash
    #- id: random-number-generator
    #  run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #  shell: bash
    #- run: |     
    #    echo "----------------------------------"
    #    cat ${{ github.action_path }}/test.log
    #     echo "----------------------------------"
    #    echo "${{ github.action_path }}"
    #    echo "----------------------------------"
    #    ls ${{ github.action_path }}
    #    echo "----------------------------------"
    #   echo "hello"
    #    ${{ github.action_path }}/goodbye.sh
    #  shell: bash
