name: 'Hello World'
description: 'Greet someone'
secrets:
  NWPS_ARTIFACTORY_USERNAME:
    required: true
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        echo "----------------------------------"
        echo ${{ secrets.NWPS_ARTIFACTORY_USERNAME }}
        echo "----------------------------------"
      shell: bash
    #- run: | 
    #    echo Hello ${{ inputs.who-to-greet }} >> ${{ github.action_path }}/test.log
    #    ls ${{ github.action_path }}
    #    cat ${{ github.action_path }}/test.log
    #  shell: bash
    #- id: random-number-generator
    #  run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #  shell: bash
    #- run: |     
    #    echo "----------------------------------"
    #    cat ${{ github.action_path }}/test.log
    #     echo "----------------------------------"
    #    echo "${{ github.action_path }}"
    #    echo "----------------------------------"
    #    ls ${{ github.action_path }}
    #    echo "----------------------------------"
    #   echo "hello"
    #    ${{ github.action_path }}/goodbye.sh
    #  shell: bash
