on:
  workflow_dispatch:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "TEST_VARIABLE=TESTING" >> $GITHUB_ENV; 
      - uses: actions/checkout@v2
      - id: foo
        uses: chriswhendricks/psint-jfrogcli/actions/setup@76381c5211e78e7732485a88b5c79246d81916f2
        #with:
        #  NWPS_ARTIFACTORY_URL: https://tylertech.jfrog.io/artifactory
        #  NWPS_ARTIFACTORY_USERNAME: ${{ secrets.NWPS_ARTIFACTORY_USERNAME }}
        #  NWPS_ARTIFACTORY_PASSWORD: ${{ secrets.NWPS_ARTIFACTORY_PASSWORD }}
          
      #- run: echo random-number ${{ steps.foo.outputs.random-number }}
      #  shell: bash

