on:
  workflow_dispatch:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:     
      ARTIFACTORY_USERNAME: "${{ secrets.NWPS_ARTIFACTORY_USERNAME }}"
      ARTIFACTORY_URL: "https://tylertech.jfrog.io/artifactory"
      ARTIFACTORY_PASSWORD: "${{ secrets.NWPS_ARTIFACTORY_PASSWORD }}"
    steps:
      - run: echo "TEST_VARIABLE=TESTING" >> $GITHUB_ENV; 
      - uses: actions/checkout@v2
      - id: foo
        uses: chriswhendricks/psint-jfrogcli/actions/setup@feat/setup-action
        #with:
        #  NWPS_ARTIFACTORY_URL: https://tylertech.jfrog.io/artifactory
        #  NWPS_ARTIFACTORY_USERNAME: ${{ secrets.NWPS_ARTIFACTORY_USERNAME }}
        #  NWPS_ARTIFACTORY_PASSWORD: ${{ secrets.NWPS_ARTIFACTORY_PASSWORD }}
          
      #- run: echo random-number ${{ steps.foo.outputs.random-number }}
      #  shell: bash

