on:
  workflow_dispatch:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "TEST_ENV=TESTING" >> $GITHUB_ENV; 
      - uses: actions/checkout@v2
      - id: foo
        uses: chriswhendricks/jfrog-cli@master
        with:
          NWPS_ARTIFACTORY_URL: https://tylertech.jfrog.io/artifactory
          NWPS_ARTIFACTORY_USERNAME: ${{ secrets.NWPS_ARTIFACTORY_USERNAME }}
          NWPS_ARTIFACTORY_PASSWORD: ${{ secrets.NWPS_ARTIFACTORY_PASSWORD }}
          
      #- run: echo random-number ${{ steps.foo.outputs.random-number }}
      #  shell: bash

